/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 *
 * @author Jelena
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblKorisnik = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        mKnjiga = new javax.swing.JMenu();
        jmiKreirajKnjigu = new javax.swing.JMenuItem();
        jmiPretraziKnjige = new javax.swing.JMenuItem();
        mClan = new javax.swing.JMenu();
        jmiKreirajClana = new javax.swing.JMenuItem();
        jmiPretraziClanove = new javax.swing.JMenuItem();
        mPTT = new javax.swing.JMenu();
        jmiPTT = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblKorisnik.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblKorisnik.setText("jLabel1");

        mKnjiga.setText("Knjiga");

        jmiKreirajKnjigu.setText("Kreiranje knjige");
        mKnjiga.add(jmiKreirajKnjigu);

        jmiPretraziKnjige.setText("Pretraživanje knjige");
        mKnjiga.add(jmiPretraziKnjige);

        menu.add(mKnjiga);

        mClan.setText("Član");

        jmiKreirajClana.setText("Kreiranje člana");
        mClan.add(jmiKreirajClana);

        jmiPretraziClanove.setText("Pretraga članova");
        mClan.add(jmiPretraziClanove);

        menu.add(mClan);

        mPTT.setText("PTT");

        jmiPTT.setText("PTT");
        jmiPTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPTTActionPerformed(evt);
            }
        });
        mPTT.add(jmiPTT);

        menu.add(mPTT);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblKorisnik, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblKorisnik)
                .addContainerGap(246, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiPTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPTTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiPTTActionPerformed

  

    public JMenuItem getJmiKreirajClana() {
        return jmiKreirajClana;
    }

    public void setJmiKreirajClana(JMenuItem jmiKreirajClana) {
        this.jmiKreirajClana = jmiKreirajClana;
    }

    public JMenuItem getJmiKreirajKnjigu() {
        return jmiKreirajKnjigu;
    }

    public void setJmiKreirajKnjigu(JMenuItem jmiKreirajKnjigu) {
        this.jmiKreirajKnjigu = jmiKreirajKnjigu;
    }

    public JMenuItem getJmiPretraziClanove() {
        return jmiPretraziClanove;
    }

    public void setJmiPretraziClanove(JMenuItem jmiPretraziClanove) {
        this.jmiPretraziClanove = jmiPretraziClanove;
    }

    public JMenuItem getJmiPretraziKnjige() {
        return jmiPretraziKnjige;
    }

    public void setJmiPretraziKnjige(JMenuItem jmiPretraziKnjige) {
        this.jmiPretraziKnjige = jmiPretraziKnjige;
    }

    public JLabel getLblKorisnik() {
        return lblKorisnik;
    }

    public void setLblKorisnik(JLabel lblKorisnik) {
        this.lblKorisnik = lblKorisnik;
    }

    public JMenu getmClan() {
        return mClan;
    }

    public void setmClan(JMenu mClan) {
        this.mClan = mClan;
    }

    public JMenu getmKnjiga() {
        return mKnjiga;
    }

    public void setmKnjiga(JMenu mKnjiga) {
        this.mKnjiga = mKnjiga;
    }

    public JMenuBar getMenu() {
        return menu;
    }

    public void setMenu(JMenuBar menu) {
        this.menu = menu;
    }

    public JMenuItem getJmiPTT() {
        return jmiPTT;
    }

    public void setJmiPTT(JMenuItem jmiPTT) {
        this.jmiPTT = jmiPTT;
    }

    public JMenu getmPTT() {
        return mPTT;
    }

    public void setmPTT(JMenu mPTT) {
        this.mPTT = mPTT;
    }
    
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jmiKreirajClana;
    private javax.swing.JMenuItem jmiKreirajKnjigu;
    private javax.swing.JMenuItem jmiPTT;
    private javax.swing.JMenuItem jmiPretraziClanove;
    private javax.swing.JMenuItem jmiPretraziKnjige;
    private javax.swing.JLabel lblKorisnik;
    private javax.swing.JMenu mClan;
    private javax.swing.JMenu mKnjiga;
    private javax.swing.JMenu mPTT;
    private javax.swing.JMenuBar menu;
    // End of variables declaration//GEN-END:variables

    public void setMax() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
}
